name: Build & Push Docker image to AWS ECR

on: push

jobs:
  build-and-push:
    name: Build & Push to AWS ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to AWS ECR
        run: |
          docker login --username AWS 137181989423.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ${{ secrets.AWS_PASSWORD }}

      - name: Build & Tag
        run: |
          docker build -t refcard03 .
          docker tag refcard03:latest 137181989423.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/refcard03:latest
          docker push 137181989423.dkr.ecr.us-east-1.amazonaws.com/refcard03:latest
