name: Build & Push Docker image to AWS ECR

on: push

jobs:
  build-and-push:
    name: Build & Push to AWS ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin 137181989423.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build, Tag, and Push
        run: |
          IMAGE_URI=137181989423.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/refcard03
          docker build -t refcard03 .
          docker tag refcard03:latest $IMAGE_URI:latest
          docker push $IMAGE_URI:latest
